title: 'Desinstalação de Aplicativo via WMIC | Behavior 10'
id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
status: test
author: 'Carlos Adriano'
description: 'Detecta a desinstalação de aplicativos usando WMIC. Este método só funciona se o produto foi instalado com um arquivo MSI.'
references:
  - 'https://attack.mitre.org/techniques/T1047'
date: '2023-09-26'
tags:
  - 'T1047'
  - 'WMI'
logsource:
  product: 'windows'
  service: 'command_line'
  category: 'process_creation'
detection:
  selection:
    Image: 'C:\\Windows\\System32\\wbem\\WMIC.exe'
    CommandLine: '*product where* call uninstall'
  condition: selection
falsepositives:
  - 'Atividades administrativas legítimas que usam WMIC para desinstalar produtos.'
level: 'medium'
